services:
  postgres:
    image: postgres:16.2
    container_name: answerly_db
    hostname: db
    networks:
      - answerly
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d answerly" ]
      interval: 10s   # Check every 10 seconds
      timeout: 5s     # Fail if it takes longer than 5 seconds
      retries: 5      # Retry 5 times before marking as unhealthy
      start_period: 10s # Wait 10s before the first check

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - answerly